---
namespace: glillico
name: server_setup
version: 1.0.0
readme: README.md

authors:
  - glillico

description: Collection of server setup and configuration tools for Ansible.

license:
  - MIT

tags:
  - build
  - configure
  - harden
  - linux
  - raspberrypi
  - server
  - setup
  - security

dependencies: {}
repository: https://github.com/glillico/ansible-collection-server_setup
documentation: https://github.com/glillico/ansible-collection-server_setup
homepage: https://github.com/glillico/ansible-collection-server_setup
issues: https://github.com/glillico/ansible-collection-server_setup/issues

build_ignore: []
